### ISSUE TITLE
Build to Remote Device fails with error code 14 "No applicable devices found"

### ISSUE THREAD

**Issue by joneill87** [Microsoft/remotebuild#14] opened 2016-12-06 19:47 UTC
Hi, I'm having trouble getting remoteBuild to work when deploying to a remote device. When trying to build to a device connected to my mac I get an error giving Error Code 70. Drilling down in the error message gives Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}

Below is the tail of the build.log generated by remoteBuild

Touch build/device/Toco\ Connect.app.dSYM
    cd /Users/jack/.taco_home/remote-builds/taco-remote/builds/34198/cordovaApp/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/jack/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/ios-sim/bin:/Users/jack/.rvm/gems/ruby-2.2.3/bin:/Users/jack/.rvm/gems/ruby-2.2.3@global/bin:/Users/jack/.rvm/rubies/ruby-2.2.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Users/jack/.rvm/bin:/Users/jack/bin:/Users/jack/.rvm/bin:/Users/jack/.rvm/bin:/Users/jack/Library/Android/sdk/tools"
    /usr/bin/touch -c /Users/jack/.taco_home/remote-builds/taco-remote/builds/34198/cordovaApp/platforms/ios/build/device/Toco\ Connect.app.dSYM

** ARCHIVE SUCCEEDED **

Non-system Ruby in use. This may cause packaging to fail.
If you use RVM, please run `rvm use system`.
If you use chruby, please run `chruby system`.
2016-12-06 14:22:45.193 xcodebuild[77107:447088] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/sb/775jkvp13lnfgrn_vz425xqw0000gn/T/Toco Connect_2016-12-06_14-22-45.191.xcdistributionlogs'.
1.2.840.113635.100.1.61
2016-12-06 14:22:48.145 xcodebuild[77107:447088] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7fa0861f09c0>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
error: exportArchive: No applicable devices found.

Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}

** EXPORT FAILED **

Failed to build app for buildNumber 34198: Error code 70 for command: xcodebuild with args: -exportArchive,-archivePath,Toco Connect.xcarchive,-exportOptionsPlist,/Users/jack/.taco_home/remote-builds/taco-remote/builds/34198/cordovaApp/platforms/ios/exportOptions.plist,-exportPath,/Users/jack/.taco_home/remote-builds/taco-remote/builds/34198/cordovaApp/platforms/ios/build/device

I looked at the logs, navigated to the directory where remoteBuild had created the .xcarchive, ran the command manually and it appeared to work. The following is the output from running the xcodebuild command manually with the arguments used by remote build

RAN THIS COMMAND MANUALLY
xcodebuild -exportArchive -archivePath Toco\ Connect.xcarchive -exportOptionsPlist /Users/jack/.taco_home/remote-builds/taco-remote/builds/34198/cordovaApp/platforms/ios/exportOptions.plist -exportPath /Users/jack/.taco_home/remote-builds/taco-remote/builds/34198/cordovaApp/platforms/ios/build/device

Got this response
2016-12-06 14:56:45.657 xcodebuild[84648:499343] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/sb/775jkvp13lnfgrn_vz425xqw0000gn/T/Toco Connect_2016-12-06_14-56-45.656.xcdistributionlogs'.
1.2.840.113635.100.1.61
Exported Toco Connect.xcarchive to: /Users/jack/.taco_home/remote-builds/taco-remote/builds/34198/cordovaApp/platforms/ios/build/device
** EXPORT SUCCEEDED **

This command generated an .ipa in the ios/build/device directory.

I've confirmed that i'm able to deploy to the device using the provisioning profile selected when I use Xcode, but can't seem to get it working with xcodebuild. I'm hoping someone can point me in the right direction, please let me know if you need any further debug info.

**Comment by MSLaguana** [comment] 2016-12-06 20:43
We don't directly run the xcodebuild command, but rather we run `cordova build ios --device` and that eventually triggers the build command. If you manually invoke the cordova build command in the project (e.g. `~/.taco_home/remote-builds/taco-remote/builds/34198/cordovaApp` if you haven't turned remotebuild off yet) does it succeed?

Are you running remotebuild as the same user that you run the commands as manually? Some data is stored per-profile, so if you are using a different user account that could possibly cause issues.

**Comment by joneill87** [comment] 2016-12-07 12:22
Hi, thanks for your help! I followed your advice and tried running `cordova build ios --device` and got an error which was resolved by forcing rvm to use system

`rvm --default use system`

I've now got to the point where remotebuild installs the app on the device, but it doesn't seem to be able to run and attach to the process. I've ensured I have the latest version of ideviceinstaller and ios_webkit_debug_proxy, and I've tried setting the appLaunch and emulatorLaunch timeout in the RemoteBuild.config to 3 minutes. I've also opened the app manually and confirmed that the remote debugger works. It doesn't seem to launch the app no matter how long I wait, and I get an error saying "We were unable to find the app you're trying to debug...".

I've created a new blank cordova app from within VisualStudio but I'm seeing the same behaviour. If I navigate to the build directory manually and run `cordova run ios --device` the app opens as expected (but I do get a notification telling me that the app may slow down my phone and needs to be updated).

Is there anything else I can try? Thanks again for your time!

**Comment by MSLaguana** [comment] 2016-12-07 16:24
One thing that I've seen occasionally is a difference in how iOS devices report console output in iOS 10, and that may make us think the app isn't launching. Do you see the app launch on your device at all? or does it sit on the home screen until it eventually times out?

Can you also please look at the console running `remotebuild` and tell me what status is reported for the `/run` command? If it is anything other than `200` then it means that we know we've failed to launch, and I suspect that will be the case.

**Comment by joneill87** [comment] 2016-12-07 20:57
Hi, thanks for the quick reply. The app doesn't launch on the device at all when I try to debug it using remotebuild. However, it does open automatically when I manually run `cordova run ios --device` in the build directory.

Strangely enough the run command reports a 404 status, but the debug command seems to be returning a 200.

**Comment by MSLaguana** [comment] 2016-12-07 21:19
The debug command is actually just starting a debug server, and that step is completing fine but then VS is communicating with the server and failing to find the running app (because the app wasn't actually launched in the first place).


In the VS output window (in the Debug tab), you should see something like 
```
Requesting launch on remote iOS device for buildNumber 75661 on server http://<MAC>:3000/cordova...
Failed to launch iOS remote for build <PROJECT>\bld\ios\Debug\buildInfo.json to http://<MAC>3000/cordova :
Http 404: Unable to read device version, is it plugged in and turned on?
```

Do you see that? What error is reported with the Http 404?

**Comment by joneill87** [comment] 2016-12-08 15:40
Thank you for your patience! The error I'm getting is

`Http 404: Unable to launch app: Cannot read property 'nodeValue' of undefined`

I did a bit of searching and came across Issue #58 in vscode-cordova which suggested the problem might be with plist-with-patches exploding when it comes across an '&' symbol in the list of installed devices. I followed the instructions there, and removed an app which had that symbol, but the error still persists. I dumped the output of ideviceinstaller -l -o xml into a file and tried to parse it using plist with patches, which gave me the same error message I'm seeing when remotebuild tries to run the app

`Cannot read property 'nodeValue' of undefined`

I checked the entire fall using an XML validator which seems to think that it's valid XML. Is there any way I can narrow down what's causing plist-with-patches to fail?

**Comment by MSLaguana** [comment] 2016-12-08 16:57
I had thought we had fixed that issue by changing from `plist-with-patches` to `plist`, but it seems that may not have been enough. Can you please try parsing your file again but using `plist.parse(fs.readFileSync(filename, 'utf8'));` where `plist = require('plist');` using plist 1.2.0 or newer?

I just saw that they have a `2.0.1` release and we are using `1.2.0` so it might be worth trying both to see if it works with 2.0.1 while breaking on 1.2.0 that we currently use.

**Comment by MSLaguana** [comment] 2016-12-08 17:15
Ah, there we go: they did fix the issue but only after a major version bump from what we depend on https://github.com/TooTallNate/plist.js/commit/4afb7c50795f90977cc8d4e9bebe2b2fabd453b3

For a temporary solution, you should be able to go to `~/.taco_home/node_modules/taco-remote-lib/2.3.0/node_modules/` and then `npm uninstall plist && npm install plist@latest` and I think that should take effect. I can't check right now, but you may have to go into `[...]/idevice-app-launcher` and run those commands instead

**Comment by joneill87** [comment] 2016-12-08 17:16
You beat me to it! Yes, the test failed in version `1.2.0` and passed using `2.0.1` so I think you've got it. I'll try the workaround for now and let you know how it goes. Thanks for your time!

**Comment by joneill87** [comment] 2016-12-08 17:53
I've just updated the plist module as you suggested. For anyone else experiencing this issue. These are the steps I followed

Navigate to `~/.taco_home/node_module/taco-remote-lib/2.2.1/node_modules/idevice-app-launcher`

Edit the package.json file and replace line 53 `"plist": "^1.2.0"` with `"plist": "~2.1.0"`

in the idevice-app-launcher folder run `npm uninstall plist && npm install plist@latest` as suggested above.

Restart remote-build.

Now when I build it launches the app as expected. However, I'm running into one lingering issue.

Even though the app launches, debugging fails with the error message

`Timed out launching the app. Check your network connection to the mac and try again. If you are launching to a device, make sure you have Web Inspector enabled on it.`

I've opened the app in Web Inspector so that's not the problem, and I'm pretty sure my Desktop can talk to the mac, because the rest of the build has gone OK. It's hanging for about 30 seconds after the app launches, and it's just the basic cordova app, so I don't think it's just timing out.

**Comment by MSLaguana** [comment] 2016-12-08 18:07
That timeout error may be due to an issue with iOS 10, if that's what you're running on the device. It's caused by a change in the (native) debugging protocol that we use to start the app. I'm going to try and get a fix for that out shortly.

However, I notice that you say you are using taco-remote-lib 2.2.1, which surprised me since we have an auto-updater and the latest version should be 2.3.0. Have you done anything to stop that from happening?

**Comment by joneill87** [comment] 2016-12-08 18:36
Not that I'm aware of. I don't do a whole lot of work with node, so I haven't really been playing around with it all that much. I've run `npm install -g remotebuild@latest` and it's coming back with remotebuild@2.1.2. Is there any way I can test the auto updater?

I have been getting a strange error every time I submit a new build, though. I really should have mentioned it before. It doesn't seem to break anything but every time I submit a build it attempts to install taco-remote-multiplexer. I get a message saying `taco-remote-multiplexer downloaded and installed` but the next line reads

`Error: ENOENT: no such file or directory, open '~/.taco_home/node_modules/taco-remote-multiplexer/tacoRemoteMultiplexer.js'`

I don't know if that may be causing the issue?

**Comment by MSLaguana** [comment] 2016-12-08 18:40
That could explain the lack of auto-updating, yes. Your version of `remotebuild` is up-to-date, but there are several components in the system and the one that auto-updates is `taco-remote-lib` (and `taco-remote-multiplexer`) and it seems that something has gone wrong there. You should be able to delete `~/.taco_home/node_modules/taco-remote-multiplexer` and restart remotebuild, and hopefully it will repair itself. Note that if you do this, we'll download the latest `taco-remote-lib` package and you may need to reapply the temporary fix above.

**Comment by joneill87** [comment] 2016-12-08 18:49
That fixed the issue, thanks! I removed the taco-remote-multiplexer directory and restarted remotebuild, it then updated the taco-remote-lib module. I am running iOS 10 which probably explains the problem debugging in Visual Studio. Thanks again for all your help getting this working!

**Comment by MSLaguana** [comment] 2016-12-08 18:52
So you can now launch and debug on your iOS 10 device correctly?

**Comment by joneill87** [comment] 2016-12-08 19:00
It does launch the app on the phone, but it doesn't attach the debugger. Did you mention that the fix for this is in the pipeline?

**Comment by MSLaguana** [comment] 2016-12-08 19:02
If VS is still complaining about the timeout on launching the app (but the app appears to actually be launched) then yes, I'm working on a fix for that.

**Comment by joneill87** [comment] 2016-12-08 19:05
Excellent, that's the stage I'm at now. Thanks again for your time!

**Comment by MSLaguana** [comment] 2016-12-12 18:25
I've just published a new version of `idevice-app-launcher` which we use to launch the app on the device. Could you please try deleting `~/.taco_home/node_modules/taco-remote-lib/2.3.0` and restarting remotebuild and see if that solves the issue for you?

**Comment by MSLaguana** [comment] 2017-01-12 00:38
I'm closing this now, but if you still have this issue then feel free to add more information and reopen.

**Closed by MSLaguana** 2017-01-12 00:38 UTC
Labels: bug
